name: i-have-seen
author: rednafi
description: |
  Automatically add a single comment every time an ISSUE or a PULL REQUEST is created.
inputs:
  message:
    description: |
      Message that will be added as an issue or pull request comment.
        Supports multi-line markdown syntax.
    default: I have seen @$(date -u --rfc-3339=s)
    required: false

  where:
    description: |
      Where the comment should be posted. Supports 'issues' and 'pull_request'.
    default: issues
    required: false

runs:
  using: "composite"
  steps:
    - users: actions/checkout@v3
    - uses: rednafi/i-have-seen/.github/workflows/seen.yml@main
      with:
        message: This is a markdown **message**.
        where: "issues"

branding:
  icon: "alert-octagon"
  color: "gray-dark"
